"""AI tool adapters — ABC with self-registering concrete implementations.

Import all adapters here to trigger __init_subclass__ registration.
"""

import threading

# Import adapters to trigger registration
import crossby.ai_tools.antigravity
import crossby.ai_tools.antigravity_cli
import crossby.ai_tools.claude
import crossby.ai_tools.codex
import crossby.ai_tools.copilot
import crossby.ai_tools.cursor
import crossby.ai_tools.opencode
import crossby.ai_tools.vscode  # noqa: F401
from crossby.ai_tools.base import AbstractAITool, pick_best_model
from crossby.ai_tools.headless import (
    HeadlessAdapterContractError,
    HeadlessCleanupHooks,
    HeadlessEventHandler,
    HeadlessInteractionHandler,
    HeadlessPreflightError,
    HeadlessRequestError,
    HeadlessRuntimeContext,
    HeadlessSchemaError,
    HeadlessSessionError,
    HeadlessTransportError,
    HeadlessUnsupportedError,
    SessionInteractionHandler,
)
from crossby.ai_tools.interactive import InteractiveLaunchHandler, InteractiveSession
from crossby.ai_tools.plan_mode import (
    PlanArtifactAmbiguousError,
    PlanArtifactLocationError,
    PlanArtifactMalformedError,
    PlanArtifactMissingError,
    PlanBindingMismatchError,
    PlanCommandPolicyUnsupportedError,
    PlanInteractionHandler,
    PlanInteractionRequiredError,
    PlanModeAdapterContractError,
    PlanModeConflictError,
    PlanModeLaunchError,
    PlanModeUnsupportedError,
    PlanSessionError,
    PlanSessionUnsupportedError,
    PlanTransportError,
    terminal_interaction_handler,
)
from crossby.models.ai import (
    AIToolID,
    HeadlessCapability,
    HeadlessEvent,
    HeadlessEventKind,
    HeadlessInteractionMode,
    HeadlessNativeOutput,
    HeadlessNativeOutputMode,
    HeadlessNativeTransport,
    HeadlessOutput,
    HeadlessOutputFormat,
    HeadlessOutputMode,
    HeadlessPreflightCheck,
    HeadlessPreflightDeferredCheck,
    HeadlessPromptTransport,
    HeadlessSessionPreflight,
    HeadlessSessionRequest,
    HeadlessSessionResult,
    HeadlessSessionStatus,
    HeadlessSessionTransport,
    HeadlessTerminalState,
    HeadlessTerminalStatus,
    HeadlessTransport,
    InteractiveLaunchEvent,
    InteractiveLaunchEventKind,
    PlanApprovalPolicy,
    PlanArtifactSource,
    PlanCommandPolicy,
    PlanCommandPolicySupport,
    PlanInteraction,
    PlanInteractionKind,
    PlanInteractionOutcome,
    PlanInteractionResponse,
    PlanNativeBindingID,
    PlanOperation,
    PlanOperationKind,
    PlanPermissionTarget,
    PlanPermissionTargetKind,
    PlanPreflightCheck,
    PlanPreflightDeferredCheck,
    PlanQuestionOption,
    PlanSessionBinding,
    PlanSessionPreflight,
    PlanSessionRequest,
    PlanSessionResult,
    SessionApprovalPolicy,
    SessionBinding,
    SessionCommandPolicy,
    SessionCommandPolicySupport,
    SessionInteraction,
    SessionInteractionKind,
    SessionInteractionOutcome,
    SessionInteractionResponse,
    SessionNativeBindingID,
    SessionOperation,
    SessionOperationKind,
    SessionOption,
    SessionPermissionTarget,
    SessionPermissionTargetKind,
    SessionQuestionOption,
    SessionTarget,
)


def preflight_headless_session(
    tool: AIToolID | str,
    request: HeadlessSessionRequest,
    interaction_handler: SessionInteractionHandler | None = None,
    *,
    timeout_seconds: float = 5.0,
    cancel_event: threading.Event | None = None,
) -> HeadlessSessionPreflight:
    """Preflight a managed ordinary session without starting its transport."""
    return AbstractAITool.get(tool).preflight_headless_session(
        request,
        interaction_handler,
        timeout_seconds=timeout_seconds,
        cancel_event=cancel_event,
    )


def preflight_plan_session(
    tool: AIToolID | str,
    request: PlanSessionRequest,
    *,
    timeout_seconds: float = 5.0,
) -> PlanSessionPreflight:
    """Preflight a complete collected session without creating workspace artifacts."""
    return AbstractAITool.get(tool).preflight_plan_session(
        request,
        timeout_seconds=timeout_seconds,
    )


__all__ = [
    "AbstractAITool",
    "HeadlessAdapterContractError",
    "HeadlessCapability",
    "HeadlessCleanupHooks",
    "HeadlessEvent",
    "HeadlessEventHandler",
    "HeadlessEventKind",
    "HeadlessInteractionHandler",
    "HeadlessInteractionMode",
    "HeadlessNativeOutput",
    "HeadlessNativeOutputMode",
    "HeadlessNativeTransport",
    "HeadlessOutput",
    "HeadlessOutputFormat",
    "HeadlessOutputMode",
    "HeadlessPreflightCheck",
    "HeadlessPreflightDeferredCheck",
    "HeadlessPreflightError",
    "HeadlessPromptTransport",
    "HeadlessRequestError",
    "HeadlessRuntimeContext",
    "HeadlessSchemaError",
    "HeadlessSessionError",
    "HeadlessSessionPreflight",
    "HeadlessSessionRequest",
    "HeadlessSessionResult",
    "HeadlessSessionStatus",
    "HeadlessSessionTransport",
    "HeadlessTerminalState",
    "HeadlessTerminalStatus",
    "HeadlessTransport",
    "HeadlessTransportError",
    "HeadlessUnsupportedError",
    "InteractiveLaunchEvent",
    "InteractiveLaunchEventKind",
    "InteractiveLaunchHandler",
    "InteractiveSession",
    "PlanApprovalPolicy",
    "PlanArtifactAmbiguousError",
    "PlanArtifactLocationError",
    "PlanArtifactMalformedError",
    "PlanArtifactMissingError",
    "PlanArtifactSource",
    "PlanBindingMismatchError",
    "PlanCommandPolicy",
    "PlanCommandPolicySupport",
    "PlanCommandPolicyUnsupportedError",
    "PlanInteraction",
    "PlanInteractionHandler",
    "PlanInteractionKind",
    "PlanInteractionOutcome",
    "PlanInteractionRequiredError",
    "PlanInteractionResponse",
    "PlanModeAdapterContractError",
    "PlanModeConflictError",
    "PlanModeLaunchError",
    "PlanModeUnsupportedError",
    "PlanNativeBindingID",
    "PlanOperation",
    "PlanOperationKind",
    "PlanPermissionTarget",
    "PlanPermissionTargetKind",
    "PlanPreflightCheck",
    "PlanPreflightDeferredCheck",
    "PlanQuestionOption",
    "PlanSessionBinding",
    "PlanSessionError",
    "PlanSessionPreflight",
    "PlanSessionRequest",
    "PlanSessionResult",
    "PlanSessionUnsupportedError",
    "PlanTransportError",
    "SessionApprovalPolicy",
    "SessionBinding",
    "SessionCommandPolicy",
    "SessionCommandPolicySupport",
    "SessionInteraction",
    "SessionInteractionHandler",
    "SessionInteractionKind",
    "SessionInteractionOutcome",
    "SessionInteractionResponse",
    "SessionNativeBindingID",
    "SessionOperation",
    "SessionOperationKind",
    "SessionOption",
    "SessionPermissionTarget",
    "SessionPermissionTargetKind",
    "SessionQuestionOption",
    "SessionTarget",
    "pick_best_model",
    "preflight_headless_session",
    "preflight_plan_session",
    "terminal_interaction_handler",
]
